### ISSUE TITLE
Fails to report error when using an object in the `style` attribute

### ISSUE THREAD

**Issue by alex-cadieux** [nmanthena18/eslint-no-inline-styles#2]
eslint does not report an error when doing this: 

```
function MyComponent() {
  const style = {height: "100%"};
  return (
    <div style={style} >This doesn't work</div>
  )
}
```

**Comment by nmanthena18** [comment]
it will work for only inline styles like this style={{ height: 40 }}, not with variables.

**Comment by JackHowa** [comment]
I'm seeing this same thing with `style={{ color: somethingRed }}` if somethingRed is a variable
